### ISSUE TITLE
(BUG)[AttysECG VERSION 1.4.0 ]  The application crashes when I try to browse the file

### ISSUE THREAD

**Issue by XAMIR555** [glasgowneuro/AttysECG#2]
#### Project Information
* Repository-----------:[Here](https://github.com/glasgowneuro/AttysECG)
* Project Name---------: [AttysECG](https://play.google.com/store/apps/details?id=tech.glasgowneuro.attysecg)
* Publisher------------: [Glasgow Neuro LTD ](https://github.com/glasgowneuro)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I try to file a browser, all the information in the file should appear in the application and the application should not be crashed.

#### Actual behavior

The app gets crashes when I try to upload or browse  file

#### How to reproduce
* [download ](https://play.google.com/store/apps/details?id=tech.glasgowneuro.attysecg)and open the application
* At the top right click three vertical dots
* click on File Browser
* select the .tsv File 
* click on the ok button
* Note the Bug

* Browser/App version-: 1.4.0
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190608_152032](https://user-images.githubusercontent.com/49812927/59145746-106d9a80-899d-11e9-81be-fb6efc3b53b5.gif)

# Logcat

<pre><code>06-08 14:44:29.523  1386  1386 E AndroidRuntime: FATAL EXCEPTION: main
06-08 14:44:29.523  1386  1386 E AndroidRuntime: Process: tech.glasgowneuro.attysecg, PID: 1386
06-08 14:44:29.523  1386  1386 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.io.PrintWriter.flush()' on a null object reference
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at tech.glasgowneuro.attysecg.AttysECG$HRRecorder.shutdown(AttysECG.java:167)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at tech.glasgowneuro.attysecg.AttysECG$HRRecorder.access$2500(AttysECG.java:131)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at tech.glasgowneuro.attysecg.AttysECG.startRRrec(AttysECG.java:588)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at tech.glasgowneuro.attysecg.AttysECG.onStart(AttysECG.java:633)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1395)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7348)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3139)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1955)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-08 14:44:29.523  1386  1386 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: FATAL EXCEPTION: main
06-08 14:44:35.874  1493  1493 E AndroidRuntime: Process: tech.glasgowneuro.attysecg, PID: 1493
06-08 14:44:35.874  1493  1493 E AndroidRuntime: java.lang.SecurityException: Permission Denial: starting Intent { act=android.settings.BLUETOOTH_SETTINGS cmp=com.android.settings/.Settings$BluetoothSettingsActivity } from ProcessRecord{c834b2bd0 1493:tech.glasgowneuro.attysecg/u0a178} (pid=1493, uid=10178) requires android.permission.BLUETOOTH_ADMIN
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3600)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4689)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4647)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5008)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4976)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at tech.glasgowneuro.attysecg.AttysECG$4.onClick(AttysECG.java:685)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:2139)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:899)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:662)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1534)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:604)
06-08 14:44:35.874  1493  1493 E AndroidRuntime: 
06-08 14:44:41.380  1689  1689 E AndroidRuntime: FATAL EXCEPTION: main
06-08 14:44:41.380  1689  1689 E AndroidRuntime: Process: tech.glasgowneuro.attysecg, PID: 1689
06-08 14:44:41.380  1689  1689 E AndroidRuntime: java.lang.SecurityException: Permission Denial: starting Intent { act=android.settings.BLUETOOTH_SETTINGS cmp=com.android.settings/.Settings$BluetoothSettingsActivity } from ProcessRecord{f1bd45bd0 1689:tech.glasgowneuro.attysecg/u0a178} (pid=1689, uid=10178) requires android.permission.BLUETOOTH_ADMIN
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1966)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1934)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1884)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3600)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4689)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4647)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5008)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:4976)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at tech.glasgowneuro.attysecg.AttysECG$4.onClick(AttysECG.java:685)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7073)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:2139)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:899)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:662)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1534)
06-08 14:44:41.380  1689  1689 E AndroidRuntime: 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:604)
</code></pre>

**Comment by berndporr** [comment]
Thanks for reporting it. I have fixed the issue and tested under Android 9 and Android 7. Let me know if that works again. I recently upgraded to androidx and that requires now a lot more security checks.

**Comment by XAMIR555** [comment]
Okay sir i am waiting for  latest updates

**Comment by XAMIR555** [comment]
Thanks u sir bug has been fixed now
