### ISSUE TITLE
AttysComm file is missing

### ISSUE THREAD

**Issue by Gagandeep0312** [glasgowneuro/AttysECG#3]
import tech.glasgowneuro.attyscomm.AttysComm is show missing. Where can I get this file.

<img width="449" alt="Screenshot 2022-02-22 at 3 48 16 PM" src="https://user-images.githubusercontent.com/83349803/155111994-e04ddc62-0ac2-4f37-9145-4ff56430e5bd.png">
;

**Comment by berndporr** [comment]
It's a separate repo: https://github.com/glasgowneuro/AttysComm
