### ISSUE TITLE
Error compiling when import modules.

### ISSUE THREAD

**Issue by carlosjvj** [glasgowneuro/AttysECG#4]
Hello, I'm trying to compile the project in Android Studio but I get errors about modules that cannot be found when importing, specifically these two that are not in the sources:
import tech.glasgowneuro.attyscomm.AttysComm;
import tech.glasgowneuro.attyscomm.AttysService;
The files are missing in the project.

Sincerely
Carlos Javier

**Comment by berndporr** [comment]
These are here: https://github.com/glasgowneuro/AttysComm you need to point your build script to this repo. https://github.com/glasgowneuro/AttysECG/blob/master/app/build.gradle#L33

**Comment by carlosjvj** [comment]
Thanks you !!!!!

👍
